// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDAaBGcOHdJMOJYHCSUGG4xm6crOfpguM',
    appId: '1:80340466304:web:a84c24ec024c47ab410465',
    messagingSenderId: '80340466304',
    projectId: 'example-app-37bee',
    authDomain: 'example-app-37bee.firebaseapp.com',
    storageBucket: 'example-app-37bee.appspot.com',
    measurementId: 'G-KZCZSHQPMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7YFzgcfhEBkEVkJNuHp_B8lSQ6Ph-NtE',
    appId: '1:80340466304:android:33707f9594d11a35410465',
    messagingSenderId: '80340466304',
    projectId: 'example-app-37bee',
    storageBucket: 'example-app-37bee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqklq7mVt_rqnGuiYK5r-CyMCpP_MQBuE',
    appId: '1:80340466304:ios:8fbea8af316b33fd410465',
    messagingSenderId: '80340466304',
    projectId: 'example-app-37bee',
    storageBucket: 'example-app-37bee.appspot.com',
    iosClientId: '80340466304-7jphtd4quvm7e5satok3f7e3bdnvoo4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.exampleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqklq7mVt_rqnGuiYK5r-CyMCpP_MQBuE',
    appId: '1:80340466304:ios:d4cf6a7a0171eb55410465',
    messagingSenderId: '80340466304',
    projectId: 'example-app-37bee',
    storageBucket: 'example-app-37bee.appspot.com',
    iosClientId: '80340466304-ls53t9o8fq2t4mofhpndnfsuikfqceqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.exampleApp.RunnerTests',
  );
}
